# -*- coding: utf-8 -*-
"""Praktikum_Analisis_Ecommerce_Fadi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGJ7apDvNszf-ovQUVB_RgQutDioaoxa
"""

import os

# GANTI isi di dalam tanda kutip di bawah ini sesuai gambar Anda:
# Username Anda biasanya ada di pojok kanan atas layar Settings Kaggle
os.environ['KAGGLE_USERNAME'] = "yuliansyahfadi"
# Copy API Token yang ada di kotak hitam di gambar Anda tadi
os.environ['KAGGLE_KEY'] = "3d9683db8f26392fdc8b2ae02ea0e70a"

# Perintah ini akan membuat folder .kaggle dan menyimpan kredensial Anda
!mkdir -p ~/.kaggle
!echo '{"username":"'$KAGGLE_USERNAME'","key":"'$KAGGLE_KEY'"}' > ~/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json

print("Konfigurasi Kaggle selesai! Sekarang Anda bisa download dataset.")

!kaggle datasets list -s "ecommerce data"

# 1. Download file zip dari Kaggle
!kaggle datasets download -d carrie1/ecommerce-data

# Ekstrak file zip
!unzip ecommerce-data.zip

import pandas as pd

# Membaca file data.csv yang ada di folder sebelah kiri
df = pd.read_csv('data.csv', encoding='ISO-8859-1')

# Melihat ringkasan data (kolom, jumlah data, dan tipe data)
df.info()

# Menampilkan 5 baris pertama
df.head()

# 1. Cek data yang kosong (Null)
print("Data Kosong:\n", df.isnull().sum())

# 2. Hapus data yang tidak punya CustomerID (karena penting untuk analisis RFM nanti)
df = df.dropna(subset=['CustomerID'])

# 3. Hapus data dengan Quantity atau UnitPrice negatif (data retur/error)
df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]

# 4. Ubah kolom InvoiceDate menjadi format tanggal yang benar
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# 5. Tambahkan kolom Total_Sales (Quantity x Harga)
df['Total_Sales'] = df['Quantity'] * df['UnitPrice']

print("\nData setelah dibersihkan:")
df.head()

import matplotlib.pyplot as plt

# Membuat kolom bulan
df['Month'] = df['InvoiceDate'].dt.to_period('M').astype(str)

# Menghitung total penjualan per bulan
monthly_sales = df.groupby('Month')['Total_Sales'].sum()

# Visualisasi
plt.figure(figsize=(12, 6))
plt.plot(monthly_sales.index, monthly_sales.values, marker='o', linestyle='-', color='b')
plt.title('Tren Total Penjualan E-commerce per Bulan', fontsize=14)
plt.xlabel('Bulan', fontsize=12)
plt.ylabel('Total Penjualan (USD)', fontsize=12)
plt.xticks(rotation=45)
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

# Menghitung 10 produk dengan kuantitas terjual terbanyak
top_products = df.groupby('Description')['Quantity'].sum().sort_values(ascending=False).head(10)

# Visualisasi
plt.figure(figsize=(10, 6))
top_products.plot(kind='barh', color='teal')
plt.title('Top 10 Produk Paling Banyak Terjual', fontsize=14)
plt.xlabel('Total Kuantitas', fontsize=12)
plt.ylabel('Nama Produk', fontsize=12)
plt.gca().invert_yaxis() # Supaya urutan yang terbanyak ada di atas
plt.show()

# Menghitung total penjualan per negara (Top 5 saja agar tidak penuh)
country_sales = df.groupby('Country')['Total_Sales'].sum().sort_values(ascending=False).head(5)

# Visualisasi
plt.figure(figsize=(8, 8))
plt.pie(country_sales, labels=country_sales.index, autopct='%1.1f%%', startangle=140, colors=['#ff9999','#66b3ff','#99ff99','#ffcc99', '#c2c2f0'])
plt.title('Proporsi Penjualan di 5 Negara Teratas')
plt.show()